config/routes.rb
Watto::Application.routes.draw do
  resources :sessions, 	only: [:new, :create, :destroy]
  resources :users, 	only: [:new, :create, :show]
  resources :addresses, only: [:new, :create, :show, :edit, :update]
  	match "addresses/update_cities/:id" => "addresses#update_cities"
  	match "addresses/update_states/:id" => "addresses#update_states"
  resources :companies, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :products, 			only: [:show, :new, :create, :edit, :update, :destroy]
  resources :reservations, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :phones,			only: [:show, :new, :create, :edit, :update, :destroy]
  	match "phones/new/:id" => "phones#new"
  resources :promotions,		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :promotion_types,	only: [:show, :new, :create, :edit, :update, :destroy]
  resources :departments, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :subdepartments, 	only: [:show, :new, :create, :edit, :update, :destroy]
  resources :payment_methods,	only: [:show, :new, :create, :edit, :update, :destroy]

  root to: 'products#index'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match "/search",  to: "application#search"

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            Existen errores en su solicitud <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_sessions_new.html.erb
<h1>Ingresa</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(:session, url: sessions_path) do |f| %>

            <%= f.label :email, "Email" %>
            <%= f.text_field :email %>

            <%= f.label :password, "Contraseña" %>
            <%= f.password_field :password %><br/>

            <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
        <% end %>
        <p>
            <%= link_to "Registro", signup_path %>
        </p>
    </div>
</div>