config/routes.rb
Watto::Application.routes.draw do
  resources :sessions, 	only: [:new, :create, :destroy]
  resources :users, 	only: [:new, :create, :show]
  resources :addresses, only: [:new, :create, :show, :edit, :update]
  	match "addresses/update_cities/:id" => "addresses#update_cities"
  	match "addresses/update_states/:id" => "addresses#update_states"
  resources :companies, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :products, 			only: [:show, :new, :create, :edit, :update, :destroy]
  resources :reservations, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :phones,			only: [:show, :new, :create, :edit, :update, :destroy]
  	match "phones/new/:id" => "phones#new"
  resources :promotions,		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :promotion_types,	only: [:show, :new, :create, :edit, :update, :destroy]
  resources :departments, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :subdepartments, 	only: [:show, :new, :create, :edit, :update, :destroy]
  resources :payment_methods,	only: [:show, :new, :create, :edit, :update, :destroy]

  root to: 'products#index'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match "/search",  to: "application#search"

end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id              :integer          not null, primary key
#  rif             :string(255)
#  commercial_name :string(255)
#  fiscal_name     :string(255)
#  description     :string(255)
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Company < ActiveRecord::Base
  attr_accessible :commercial_name, :description, :fiscal_name, :rif, :phones_attributes

  belongs_to :user
  has_many :products
  has_many :phones, dependent: :destroy
  has_many :promotions, dependent: :destroy

  validates :user_id, presence: true

  accepts_nested_attributes_for :phones

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :destroy, :update, :edit]

  def new
    @company = Company.new
    @phone_types = ["Casa", "Oficina", "Movil"]
  	3.times do
    	@company.phones.build
    end
  end

  def index
    @companies = Company.all.paginate(page: params[:page])
  end

  def show
    @company = Company.find(params[:id])
    @products = @company.products.paginate(page: params[:page])
  end

  def create
    @company = current_user.companies.build(params[:company])
    if @company.save
      flash[:sucess] = "La empresa #{@company.commercial_name} ha sido creada."
      redirect_to @company
    else
      render "new"
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(params[:company])
      flash[:sucess] = "La empresa #{@company.commercial_name} ha sido modificada."
      redirect_to @company
    else
      render "edit"
    end
  end

  def destroy
    Company.find(params[:id]).destroy
    redirect_to current_user
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<li id="<%= company.id %>">
  <span class="commercial_name">
    <b><%= link_to "#{company.commercial_name}", company %></b>
  </span>
  <span class="fiscal_name"><%= company.fiscal_name %></span>
  <span class="description"><%= company.description %></span>
  <% if current_user?(company.user) %>
    <%= link_to "Editar Compañía", edit_company_path(company) %>
  <% end %>
  <%= render "companies/company_delete_button", item: company %>
</li>

app/views/companies/_company_delete_button.html.erb
<% if current_user?(item.user) %>
  <%= button_to "Borrar", item, class: "btn btn-danger", method: :delete,
    data: { confirm: "You sure?" },
    title: item.commercial_name %>
<% end %>

app/views/companies/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :rif %>
<%= f.text_field :rif %>

<%= f.label :commercial_name %>
<%= f.text_field :commercial_name %>

<%= f.label :fiscal_name %>
<%= f.text_field :fiscal_name %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= render 'phones/fields', f:f %>

app/views/companies/edit.html.erb
<h1>Editando: <%= @company.commercial_name %></h1>

<div class="row">
	<div class="span4 offset4">
    <%= form_for(@company) do |f| %>
      <%= render 'fields', f:f %>
      <%= f.submit "Guardar cambios", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/companies/new.html.erb
<h1>Agrega una compañía</h1>

<div class="row">
	<div class="span4 offset4">
    <%= form_for(@company) do |f| %>
      <%= render 'fields', f:f %>
      <%= f.submit "Crear compañía", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/companies/show.html.erb
<aside>
  <section>
    <h1><%= @company.commercial_name %></h1>
    <span class="fiscal_name"><%= @company.fiscal_name %></span>
    <span class="description"><%= @company.description %></span>
    <%= link_to "Nuevo Producto", new_product_path(company: @company), class: "btn btn-primary" %>
    <%= link_to "Nuevo Promocion", new_promotion_path(company: @company), class: "btn btn-primary" %>
    <ol class="products">
      <h2>Productos</h2>
      <%= render @products %>
    </ol>
    <%= will_paginate @products %>
  </sectin>
</aside>