config/routes.rb
Watto::Application.routes.draw do
  resources :sessions, 	only: [:new, :create, :destroy]
  resources :users, 	only: [:new, :create, :show]
  resources :addresses, only: [:new, :create, :show, :edit, :update]
  	match "addresses/update_cities/:id" => "addresses#update_cities"
  	match "addresses/update_states/:id" => "addresses#update_states"
  resources :companies, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :products, 			only: [:show, :new, :create, :edit, :update, :destroy]
  resources :reservations, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :phones,			only: [:show, :new, :create, :edit, :update, :destroy]
  	match "phones/new/:id" => "phones#new"
  resources :promotions,		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :promotion_types,	only: [:show, :new, :create, :edit, :update, :destroy]
  resources :departments, 		only: [:show, :new, :create, :edit, :update, :destroy]
  resources :subdepartments, 	only: [:show, :new, :create, :edit, :update, :destroy]
  resources :payment_methods,	only: [:show, :new, :create, :edit, :update, :destroy]

  root to: 'products#index'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match "/search",  to: "application#search"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Aplicación Demo</a>
    by AA LD SP
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
		<div class="nav  pull-left">
          <%= image_tag("Logo_Base.png", :class => "img-rounded") %>
		</div>
		<div class="nav">
			<%= form_tag("/search", :method => "get", :class => "navbar-form") do %>
				<ul class="nav">
					<li><br/>
						<%= text_field_tag :name, nil, :class => "search-query input-xxlarge", :placeholder => "Buscar Producto..."%>
					</li>
				</ul>
			<% end %>
        </div>
        <ul class="nav">
          <% if signed_in? %>
            <li><%= link_to "Home", current_user %></li>
            <li><%= link_to "Compañias", new_company_path %></li>
            <li><%= link_to "Direcciones", new_address_path %></li>
            <li><%= link_to "Salir", signout_path, method: "delete" %></li>
          <% else %>
            <div class="header">
              <li><%= link_to "Ingresar", signin_path %></li>
              <li><%= link_to "Registrarse", new_user_path %></li>
              <li><%= link_to "Olvido su contraseña?", signin_path %></li>
            </div>
          <br/>
          <% end %> 
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_search.html.erb
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit "Buscar", class: "btn btn-mini btn-info" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  	<!--[if lt IE 9] 
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script> -->
	<!--[endif]-->
</head>

<body>
	<%= render 'layouts/header' %>
	<br/><br/><br/>
  	<div class="container">
    	<% flash.each do |key, value| %>
      		<div class="alert alert-<%= key %>"><%= value %></div>
    	<% end %>
    	<%= yield %>
    	<%= render 'layouts/footer' %>
    	<%= debug(params) if Rails.env.development? %>
  	</div>
</body>
</html>